// Code generated by mockery v1.0.0. DO NOT EDIT.

package core

import (
	"github.com/stretchr/testify/mock"
)

// MockMiddleware is an autogenerated mock type for the Middleware type
type MockMiddleware struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx
func (_m *MockMiddleware) Handle(ctx Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Priority provides a mock function with given fields:
func (_m *MockMiddleware) Priority() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// SetNext provides a mock function with given fields: next
func (_m *MockMiddleware) SetNext(next Middleware) {
	_m.Called(next)
}
